# Generated by Django 2.1.7 on 2019-07-12 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LostAndFound', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostandfound',
            name='image',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
