# Generated by Django 2.1.7 on 2019-07-12 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LostAndFound', '0002_lostandfound_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostandfound',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
