# Generated by Django 2.1.7 on 2019-07-12 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LostAndFound', '0003_auto_20190712_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostandfound',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
