# Generated by Django 2.1.7 on 2019-07-14 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LostAndFound', '0004_auto_20190712_1838'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_created', models.DateTimeField(auto_now_add=True)),
                ('comment_writer', models.CharField(max_length=200)),
                ('comment_text', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='lostandfound',
            name='image',
        ),
        migrations.AddField(
            model_name='comment',
            name='lost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='LostAndFound.LostAndFound'),
        ),
    ]
