# Generated by Django 2.1.7 on 2019-07-15 08:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('LostAndFound', '0005_auto_20190715_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostandfound',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
