# Generated by Django 2.1.7 on 2019-07-20 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LostAndFound', '0006_lostandfound_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_created',
            field=models.DateField(verbose_name='date published'),
        ),
    ]
